
import React from 'react';
import './App.css';
import ArticlePreview from './ArticlePreview';
import Header from './Header';

class App extends React.Component {

  render() {
    return (
      <div className="clear-margin">
        <Header />
        <div className="container">
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
          <ArticlePreview className="article-preview" srcImg="https://via.placeholder.com/150" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum ultricies ipsum. Nulla ornare purus eget malesuada sollicitudin. Pellentesque lobortis, nunc ac sagittis euismod, eros nunc gravida turpis, sit amet gravida elit ipsum ac ipsum. Nunc dignissim iaculis lectus, ut placerat leo consectetur vel. Vivamus eu malesuada nunc. Donec gravida neque id purus sodales elementum. Nam porta odio a egestas aliquet. Nunc id erat neque. Mauris sagittis mattis eros in luctus. Nullam at posuere magna. Suspendisse dignissim nulla eget enim laoreet, quis ornare quam finibus." />
        </div>
      </div>
    );
  }

}

export default App;